# Generated by Django 5.0.4 on 2024-04-15 00:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_ticket_admins'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='admins',
            field=models.ManyToManyField(blank=True, null=True, related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
